namespaces:
    CCDNUserAdminBundle: CCDNUser\AdminBundle\Form\Validator\Constraints\

%ccdn_user_admin.entity.user.class%:
    properties:
        username:
            - Type: { type: string, groups: [update_account] }
            - Length: { min: 4, groups: [update_account] }
            - NotNull: { groups: [update_account] }
        email:
            - Type: { type: string, groups: [update_account] }
            - Length: { min: 5, groups: [update_account] }
            - NotNull: { groups: [update_account] }

#Role:
#    properties:
#        new_role:
#            - Type: { type: string, groups: [update_account_roles] }
#            - MinLength: { limit: 255, groups: [update_account_roles] }
#            - NotNull: { groups: [update_account_roles] }
